### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by MoonTreee** [wycm/zhihu-crawler#16]
java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at com.crawl.core.util.SimpleLogger.setLogProperty(SimpleLogger.java:18)
	at com.crawl.core.util.SimpleLogger.getSimpleLogger(SimpleLogger.java:38)
	at com.crawl.Main.<clinit>(Main.java:13)
Exception in thread "main"

**Comment by wycm** [comment]
应该是项目配置的问题，properties文件没有被加载到

**Comment by MoonTreee** [comment]
多谢  是我太疏忽了！现已解决。
