### ISSUE TITLE
初始化authoriztion失败

### ISSUE THREAD

**Issue by gustave001** [wycm/zhihu-crawler#27]
Exception in thread "main" java.lang.RuntimeException: not get authorization
	at com.crawl.zhihu.ZhiHuHttpClient.initAuthorization(ZhiHuHttpClient.java:168)
	at com.crawl.zhihu.ZhiHuHttpClient.getAuthorization(ZhiHuHttpClient.java:173)
	at com.crawl.zhihu.ZhiHuHttpClient.startCrawl(ZhiHuHttpClient.java:114)
	at com.crawl.Main.main(Main.java:15)

**Comment by wycm** [comment]
已修复
