### ISSUE TITLE
登陆成功，紧接着出现的提示不知怎么回事

### ISSUE THREAD

**Issue by yukon2100** [wycm/zhihu-crawler#6]
谢谢大神的代码，我刚学java。
跑的时候出现这个问题
Exception in thread "pool-1-thread-1" java.lang.NullPointerException
	at com.crawl.parser.zhihu.ZhiHuUserIndexDetailPageParser.parseUserdetail(ZhiHuUserIndexDetailPageParser.java:44)
	at com.crawl.parser.zhihu.ZhiHuUserIndexDetailPageParser.parse(ZhiHuUserIndexDetailPageParser.java:30)
	at com.crawl.zhihu.task.ParseTask.parse(ParseTask.java:56)
	at com.crawl.zhihu.task.ParseTask.run(ParseTask.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
请问怎么解决

**Comment by yukon2100** [comment]
具体的就是
 u.setUsername(doc.select(".title-section a").first().text());//用户名
 return parseUserdetail(doc);

User u = parser.parse(page);
 public void run() {
        parse();
    }
的问题

**Comment by wycm** [comment]
空指针因为知乎页面最近在改版，不过现在已经解决了。你更新下代码

**Comment by LINGLUOJUN** [comment]
超赞，我很久以前也是打算模拟登录知乎的，但是并不能成功，然后放弃了。作者这个直接就能运行，太棒了，又一次激发了我弄爬虫的热情
